let CreditsFrame_Font = {
    render: function (displayOutput, width, height, buildType) {
        let text = "The font used in this game was generated by metaflop and then \n"
            + "slightly modified by dtsudo. \n"
            + "https://www.metaflop.com/modulator \n"
            + "\n"
            + "The font is licensed under SIL Open Font License v1.1 \n"
            + "See the source code for more details about the license. \n";
        displayOutput.drawText(10, height - 10, text, 0 /* GameFont.SimpleFont */, 27, black);
    }
};
